steps:
- name: 'alpine'
  args: ['mvnw', 'package']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'src/main/docker/Dockerfile.jvm', '-t', 'gcr.io/$PROJECT_ID/quarkus-tutorial', '.' ]
images:
- 'gcr.io/$PROJECT_ID/quarkus-tutorial'