# gcloud alpha builds triggers import --source .cloudbuild/trigger-master.yaml
name: quarkus-tutorial-master
description: Master
filename: .cloudbuild/cloudbuild-master.yaml
github:
  name: quarkus-tutorial
  owner: luca-poddigue
  push:
    branch: master
ignoredFiles:
  - .gitignore
  - .cloudbuild/trigger-*.yaml
  - '*.txt'
  - '*.md'