# gcloud alpha builds triggers import --source .cloudbuild/trigger-pr.yaml
name: quarkus-tutorial-pr
description: Pull Request
filename: .cloudbuild/cloudbuild-pr.yaml
github:
  name: quarkus-tutorial
  owner: luca-poddigue
  pullRequest:
    branch: .*
ignoredFiles:
  - .gitignore
  - .cloudbuild/trigger-*.yaml
  - '*.txt'
  - '*.md'